require(ggplot2)
require(shiny)
require(plotly)
require(wesanderson)
require(sas7bdat)
require(haven)
require( shinydashboard)
require(forecast)
load( 'Datos.Rdata')
shinyApp(ui = ui,server = server)
